import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import QuizCard from "../components/QuizCard";
import { useState } from "react";
import {shuffleArray } from "./mockData";

type ScoreReport = {
  answeredQuestions: number;
  totalQuestions: number;
  correctAnswers: number;
};

type Kana = {
  displayValue: string; correctAnswer: string
}
type HomePageProps = {
  data: Kana[] 
}
const Home: NextPage<HomePageProps> = (props: HomePageProps) => {
  const [score, setScore] = useState<ScoreReport>({
    answeredQuestions: 0,
    correctAnswers: 0,
    totalQuestions: props.data.length,
  });

  const onAnswer = (answeredCorrectly: boolean) => {
    if (answeredCorrectly) {
      setScore((prevState) => {
        return {
          ...prevState,
          correctAnswers: prevState.correctAnswers + 1,
          answeredQuestions: prevState.answeredQuestions + 1,
        };
      });
    } else {
      setScore((prevState) => {
        return {
          ...prevState,
          answeredQuestions: prevState.answeredQuestions + 1,
        };
      });
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}></h1>

        <p className={styles.description}>
          Test your kana knowledge!
          {score.answeredQuestions === score.totalQuestions && (
            <div className={styles.code}>
              Your score is{" "}
              {parseFloat(
                (score.correctAnswers / score.totalQuestions).toFixed(3)
              ) * 100}
              %
            </div>
          )}
        </p>

        <div className={styles.grid}>
          {props.data.map((data, i) => {
            return <QuizCard key={i} onAnswer={onAnswer} {...data} />;
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}></span>
        </a>
      </footer>
    </div>
  );
};

export async function getServerSideProps() {
  const res = await fetch("http://localhost:8000/kana");
  const data:  Kana[] = await res.json();
  return { props: { data: shuffleArray(data) } };
}

export default Home;
